Create tech-speech.md
philippranzhin/peredelanoconf pull request #34
Opened 2023-07-24 16:20 UTC by philippranzhin

Добавлено описание рекомендаций к техническим докладам на Peredelanoconf

2023-07-24 16:26 UTC, shashkovdanil requested changes

2023-07-24 16:26 UTC, shashkovdanil commented on guides/tech-speech.md
> +# Технические выступления на **Peredelanoconf**
Я не знаю в этом документе это должно быть или нет, но мне кажется, что сюда нужно еще добавить что делать если ты хочешь выступить: к кому обращаться, как понять, что твой доклад заппрувили, могут ли его не заапрувить и тд.

2023-07-24 16:31 UTC, ai commented on guides/tech-speech.md
> +Вместо сессии Q&A предполагается, что слушатели начнут обсуждать друг с другом и со спикером поднятую тему — воспроизводим формат "обусждение в курилке"
```suggestion
Вместо сессии Q&A предполагается, что слушатели начнут обсуждать друг с другом и со спикером поднятую тему уже после выступления — воспроизводим формат "обусждение в курилке"
```

Как-то надо подчеркнуть, что речь о том, что обсуждения идут «на афтепати».

2023-07-24 17:18 UTC, aesilevich commented
Всё-таки хотелось бы иметь возможность делать доклад со слайдами, если есть возможность. Но не знаю насколько это осуществимо по финансовым затратам.

2023-07-24 17:20 UTC, aesilevich commented
Предлагаю добавить в текст допустимость использования слайдов в случае, если на мероприятии будет такая возможность. Т. е. спикер должен заранее согласовать это с организаторами.

2023-07-24 17:24 UTC, philippranzhin commented
> Всё-таки хотелось бы иметь возможность делать доклад со слайдами, если есть возможность. Но не знаю насколько это осуществимо по финансовым затратам.

Смотри, отсутствие слайдов диктуется не невозможностью это осуществить — с этим как раз нет никаких проблем

Слайды меняют формат в корне: они подразумевают серьезную подготовку, и превращают спитч в лекцию, так же они поощряют стремление дать больше информации, утяжелить материал

Это именно то, от чего мы хотим уйти. При том что этот документ носит рекомендательный характер, и спикеры всё-таки могут потребовать себе инструменты для слайдов, могут сделать более длинное сложное выступление, чем у нас принято — мы пойдём навстречу

Но хочется всё же донести, что в нашем формате лучше всего зайдёт именно короткая речь без опоры на визуальную информацию

2023-07-24 17:32 UTC, aesilevich commented
> Слайды меняют формат в корне: они подразумевают серьезную подготовку, и превращают спитч в лекцию, так же они поощряют стремление дать больше информации, утяжелить материал

Слайды требуют дополнительной подготовки, это действительно так. Но они не обязательно превращают доклад в большую длинную лекцию. Это же на самом деле зависит от того, что на слайдах показывать.

Я просто не очень представляю как можно делать доклад про технические вещи без примеров кода, особенно если собралась аудитория из разных областей. Если людям в контексте конерктного языка/фреймворка можно ещё как-то объяснить на пальцах, то люди вне контекста вообще ничего не поймут.

2023-07-24 19:26 UTC, proggga commented
Плюсую автору 

> Если людям в контексте конерктного языка/фреймворка можно ещё как-то объяснить на пальцах, то люди вне контекста вообще ничего не поймут.

Плюс, я считаю что если вы даете возможность людям прогнать доклад где точно не обстебут, то некоторые захотят прогнать свой доклад для большой конфы/аудитории на более мелкой локальной, но это моя хотелка

2023-07-25 00:01 UTC, dorjechang commented
На мой взгляд, при всей оригинальности peredelano.conf, кое-что похожее не по форме, но по идее, найти не сложно. Для меня таковой аналогией безоговорочно является TED Talks. Это мероприятие — не учебная сессия, оно не ориентировано на каких-то отдельно взятых хуйзнаетчегоендеров, в роли участников там в своей тарелке чувствует себя абсолютно любой человек, хоть как-то причастный и/или заинтересованный в теме спича. И при этом абсолютное большинство спичей на TED проходит без всяких слайдов. Максимум — whiteboard или что-то подобное.

В этой части я предложенный @philippranzhin формат однозначно поддерживаю: цель спича на таких тусовках должно соответствовать целям тусовки. А peredelano.conf задумана, сдаётся мне, вовсе не как глубоко техническая конференция, и цели её — не научить использовать нечто, а заинтересовать и мотивировать использовать. Для этого нужно рассказывать не **как** использовать, а **что** это даст.

Не надо превращать отличный, призванный знакомиться, общаться, отдыхать и мотивировать на просвещение замысел в скучные для тех, кто знает, и совершенно непонятные для тех, кто не в теме, How-To-лекции.

2023-07-25 04:36 UTC, nahuka3 commented
> Я был уверен гайд будет чуть подробнее, скорее увидел набор мотивационных фраз. Хочется небольшой фак
> 
> "А я хочу презу, совсем не как?" "Куда мне записаться если хочу рассказать, на месте или заранее?" "У меня спорный тейк не про айти, стоит его нести" "Сколько у меня времени, есть ли стоппер или орг который меня остановит?" "Будет ли бонус за доклад или это для себя?" "Будут ли прогоны докладов с организаторами или все на мой и ваш страх и риск?"

1) В зависимости от того, как вольется этот пул реквест, но, лично мое мнение, презентации не нужны
Опять таки, я — не кодер, но если бы рассказывал какую-то техничку — без слайдов бы справился

2) Тут есть два варианта — с подготовкой и без. 
С — до ивента списаться с аудиторией/организатором, выяснить интересную тему, подготовить ее и выступить
Без — просто в освободившиеся время взять микрофон и начать спич

3) Зависит от цели — выступая на конфе перед публикой стоит ставить себе конкретную задачу для выступления, что ты вообще ждешь от него? Хочешь просвящаться — пожалуйста, создать обсуждение — велкам, поучиться выступать на сцене — легко. Тема, форма и подача — на усмотрнение спикера. Конфа — площадка

4) Наша рекомендация — от 15 до 30 минут со всеми вытекающими. Никто не побежит отнимать у тебя микрофон посреди выступления, но по взгляду на орга/аудиторию можно легко понять, что ты уже вышел за тайминг и пора ли сворачиваться

5) Выступление у нас на конфе для спикера — и есть бонус

6) Прогон — по запросу спикера. Если чувствуешь необходимость предварительно подготовиться и прогнать выступления — связываешься с оргами, приходишь пораньше, готовишься, мы — помогаем

2023-07-25 07:11 UTC, kroq86 reviewed
Нужно добавить информацию о том что для Спикера участие в Конференции бесплатное, исключение открытый микрофон

2023-07-25 08:36 UTC, proggga commented
@nahuka3 спасибо за ответ, я предлагаю эти пункты добавить в PR, в файл, и может вы сможете добавить в файл еще парочку F.A.Q. а не только комментов в issue

2023-07-25 12:27 UTC, closed without merging